# Generated by cucumber-sinatra. (Wed Jun 08 21:09:46 +0200 2011)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/sopserve.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = SopServe

class SopServeWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SopServeWorld.new
end
